name: Bug report
description: Something is not working
title: "[Bug] "
labels: [fix]
body:
  - type: input
    id: version
    attributes:
      label: TWANTS version
      placeholder: 0.1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Minimal reproduction
      render: html
    validations:
      required: true
