name: Feature request
description: Suggest a new component or improvement
title: "[Feature] "
labels: [feat]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
